### Join Group
POST http://localhost/api/connection/join
Content-Type: application/json

{
  "groupId": 1,
  "userId": 1
}

### Get all users in a specific group
GET http://localhost/api/connection/group/1
Accept: application/json

### Get all groups that a specific user is a member of
GET http://localhost/api/connection/user/3
Accept: application/json

### Leave Group
DELETE http://localhost/api/connection/1/1
