### Create group
POST http://localhost/api/group
Content-Type: application/json

{
  "categoryId": 11,
  "leaderId": 2,
  "name": "new group",
  "desc": null,
  "groupImageUrl": null,
  "publicType": "PRIVATE",
  "maxNum": 100,
  "cityId": 5,
  "townId": 3
}

### Update group
PATCH http://localhost/api/group
Content-Type: application/json

{
  "groupId": 1,
  "categoryId": 11,
  "leaderId": 2,
  "name": "new group - update",
  "desc": null,
  "groupImageUrl": null,
  "publicType": "PUBLIC",
  "maxNum": 100,
  "cityId": 5,
  "townId": 3
}

### Delete group
DELETE http://localhost/api/group/1



### Get all posts in a specific group
GET http://localhost/api/post/1
Accept: application/json

### Create post
POST http://localhost/api/post
Content-Type: application/json

{
  "groupId": 2,
  "writerId": 1,
  "writerEmail": "test00@gmail.com",
  "writerName": "tester00",
  "contents": "new post content",
  "publicType": "MEMBER"
}

### Update post
PATCH http://localhost/api/post
Content-Type: application/json

{
  "postId": 1,
  "groupId": 1,
  "contents": "update content",
  "publicType": "PUBLIC"
}

### Delete post
DELETE http://localhost/api/post/133
