### Create group
POST http://localhost/api/group
Content-Type: application/json

{
  "categoryId": 11,
  "leaderId": 2,
  "name": "new group",
  "desc": null,
  "groupImageUrl": null,
  "publicType": "PRIVATE_GROUP",
  "maxNum": 100,
  "cityId": 5,
  "townId": 3
}

### Update group
PATCH http://localhost/api/group
Content-Type: application/json

{
  "groupId": 1,
  "categoryId": 11,
  "leaderId": 2,
  "name": "new group - update",
  "desc": null,
  "groupImageUrl": null,
  "publicType": "PUBLIC_GROUP",
  "maxNum": 100,
  "cityId": 5,
  "townId": 3
}




### Get all posts in a specific group
GET http://localhost/api/post/1
Accept: application/json

### Create post
POST http://localhost/api/post
Content-Type: application/json

{
  "groupId": 2,
  "writer": {
    "userId": 1,
    "email": "test00@gmail.com",
    "name": "tester00"
  },
  "contents": "new post content",
  "publicType": "PRIVATE_POST"
}

### Update post
PATCH http://localhost/api/post
Content-Type: application/json

{
  "postId": 1,
  "groupId": 1,
  "contents": "update content",
  "publicType": "PRIVATE_POST"
}

### Delete post
DELETE http://localhost/api/post/1
